import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { resolveAdapters } from "../adapters/index.js";
import { MANAGED_END, MANAGED_START } from "../adapters/shared.js";
import { loadConfig } from "../loadConfig.js";
import type { AdapterId } from "../types.js";

export interface SyncOptions {
  dir: string;
  adapters?: AdapterId[];
}

export interface SyncSkip {
  path: string;
  reason: string;
}

export interface SyncResult {
  created: string[];
  updated: string[];
  unchanged: string[];
  skipped: SyncSkip[];
}

// Replaces only the block between MANAGED_START/MANAGED_END, preserving
// everything outside it byte-for-byte. Returns undefined if the existing
// file has no managed block at all - it's then indistinguishable from a
// fully hand-authored file, so sync must not touch it.
function spliceManaged(existing: string, freshManagedBlock: string): string | undefined {
  const startIdx = existing.indexOf(MANAGED_START);
  const endIdx = existing.indexOf(MANAGED_END);
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    return undefined;
  }
  const before = existing.slice(0, startIdx);
  const after = existing.slice(endIdx + MANAGED_END.length);
  return `${before}${freshManagedBlock}${after}`;
}

export async function runSync(options: SyncOptions): Promise<SyncResult> {
  const result: SyncResult = { created: [], updated: [], unchanged: [], skipped: [] };

  const loaded = await loadConfig(options.dir);
  if (!loaded.ok) {
    const message =
      loaded.reason === "missing"
        ? `No engineering-loop.json found in ${options.dir}. Run \`engineering-loop init\` first.`
        : `engineering-loop.json is invalid (${loaded.reason}): ${loaded.detail}`;
    throw new Error(message);
  }

  const config = loaded.config;
  const adapterIds =
    options.adapters && options.adapters.length > 0 ? options.adapters : (config.adapters ?? []);
  const adapters = resolveAdapters(adapterIds);

  await mkdir(options.dir, { recursive: true });

  for (const adapter of adapters) {
    const outputPath = join(options.dir, adapter.outputPath);
    const fresh = adapter.render(config);

    if (!existsSync(outputPath)) {
      await writeFile(outputPath, `${fresh}\n`, "utf-8");
      result.created.push(outputPath);
      continue;
    }

    const existing = await readFile(outputPath, "utf-8");
    const spliced = spliceManaged(existing, fresh);

    if (spliced === undefined) {
      result.skipped.push({
        path: outputPath,
        reason:
          "no managed block found (hand-authored, or generated by a pre-1.1.0 CLI) - edit manually or delete and re-run init",
      });
      continue;
    }

    if (spliced === existing) {
      result.unchanged.push(outputPath);
      continue;
    }

    await writeFile(outputPath, spliced, "utf-8");
    result.updated.push(outputPath);
  }

  return result;
}
