import type { EngineeringLoopConfig } from "../types.js";
import type { Adapter } from "./types.js";
import {
  LOOP_PHASES,
  MANIFESTO_PRINCIPLES,
  renderCommandsBlock,
  renderLanguagePolicyLine,
  renderMemorySection,
} from "./shared.js";

function render(config: EngineeringLoopConfig): string {
  const name = config.project.name;
  const manifesto = MANIFESTO_PRINCIPLES.map((p) => `* ${p}`).join("\n");
  const phases = LOOP_PHASES.map((p, i) => `${i + 1}. ${p}`).join("\n");
  const commands = renderCommandsBlock(config);

  return `# Conventions — ${name}

Pass this file to Aider with \`--read CONVENTIONS.md\` (or add it to
\`.aider.conf.yml\`). Generated by the ELS Aider adapter from
\`engineering-loop.json\`.

## Engineering principles

${manifesto}

## Language policy

${renderLanguagePolicyLine(config)}

## Loop to follow for non-trivial changes

${phases}

## Project memory

${renderMemorySection(config)}
${commands.length > 0 ? `\n## Verification commands\n\n${commands.join("\n")}\n` : ""}`;
}

export const aiderAdapter: Adapter = {
  id: "aider",
  label: "Aider",
  outputPath: "CONVENTIONS.md",
  render,
};
