import type { EngineeringLoopConfig } from "../types.js";
import type { Adapter } from "./types.js";
import {
  LOOP_PHASES,
  MANIFESTO_PRINCIPLES,
  renderCommandsBlock,
  renderLanguagePolicyLine,
  renderMemorySection,
} from "./shared.js";

function render(config: EngineeringLoopConfig): string {
  const name = config.project.name;
  const manifesto = MANIFESTO_PRINCIPLES.map((p, i) => `${i + 1}. **${p}**`).join("\n");
  const phases = LOOP_PHASES.map((p, i) => `${i + 1}. ${p}`).join("\n");
  const commands = renderCommandsBlock(config);

  return `# CLAUDE.md - ${name}

Generated by the Engineering Loop Standard (ELS) Claude Code adapter. This
file is the binding contract for Claude Code working in this repository. See
\`engineering-loop.json\` for the machine-readable source of truth this file
is generated from.

## Agentic Engineering Manifesto

${manifesto}

## Language policy

${renderLanguagePolicyLine(config)} This applies even when the human author
writes to Claude in a different language.

## The 10-phase engineering loop

For any non-trivial change (feature, bugfix, refactor, infra), work through:

${phases}

## Persistent memory

${renderMemorySection(config)}

${commands.length > 0 ? `## Commands\n\n${commands.join("\n")}\n` : ""}
`;
}

export const claudeAdapter: Adapter = {
  id: "claude",
  label: "Claude Code",
  outputPath: "CLAUDE.md",
  render,
};
