import type { EngineeringLoopConfig } from "../types.js";
import type { Adapter } from "./types.js";
import {
  LOOP_PHASES,
  MANIFESTO_PRINCIPLES,
  renderCommandsBlock,
  renderLanguagePolicyLine,
  renderMemorySection,
} from "./shared.js";

function render(config: EngineeringLoopConfig): string {
  const name = config.project.name;
  const manifesto = MANIFESTO_PRINCIPLES.map((p, i) => `${i + 1}. ${p}`).join("\n");
  const phases = LOOP_PHASES.map((p, i) => `${i + 1}. ${p}`).join("\n");
  const commands = renderCommandsBlock(config);

  return `# AGENTS.md — ${name}

Read by Codex, Gemini, and any other agent that honors the AGENTS.md
convention. Generated by the ELS adapter from \`engineering-loop.json\`.

## Manifesto

${manifesto}

## Language policy

${renderLanguagePolicyLine(config)}

## Engineering loop

For any non-trivial change, work through:

${phases}

## Memory

${renderMemorySection(config)}
${commands.length > 0 ? `\n## Commands\n\n${commands.join("\n")}\n` : ""}`;
}

export const codexAdapter: Adapter = {
  id: "codex",
  label: "Codex / Gemini",
  outputPath: "AGENTS.md",
  render,
};
