import type { EngineeringLoopConfig } from "../types.js";
import type { Adapter } from "./types.js";
import {
  LOOP_PHASES,
  MANIFESTO_PRINCIPLES,
  renderCommandsBlock,
  renderLanguagePolicyLine,
  renderMemorySection,
  wrapManaged,
} from "./shared.js";

function render(config: EngineeringLoopConfig): string {
  const name = config.project.name;
  const manifesto = MANIFESTO_PRINCIPLES.map((p) => `- ${p}`).join("\n");
  const phases = LOOP_PHASES.map((p, i) => `${i + 1}. ${p}`).join("\n");
  const commands = renderCommandsBlock(config);

  return wrapManaged(`# ${name} — Engineering Loop Standard rules

Generated by the ELS Cursor adapter from \`engineering-loop.json\`. Content
outside the markers below survives \`engineering-loop sync\`.

## Principles

${manifesto}

## Language policy

${renderLanguagePolicyLine(config)}

## Loop

Work through this sequence for any non-trivial change:

${phases}

## Memory

${renderMemorySection(config)}
${commands.length > 0 ? `\n## Commands\n\n${commands.join("\n")}\n` : ""}`);
}

export const cursorAdapter: Adapter = {
  id: "cursor",
  label: "Cursor",
  outputPath: ".cursorrules",
  render,
};
