import type { EngineeringLoopConfig } from "../types.js";

// `engineering-loop sync` re-renders only the block between these markers,
// leaving anything a human added above/below it untouched. A file with no
// markers at all (hand-authored, or generated by a pre-1.1.0 CLI) is never
// touched by sync - it's indistinguishable from a fully hand-written file.
export const MANAGED_START = "<!-- engineering-loop:managed:start -->";
export const MANAGED_END = "<!-- engineering-loop:managed:end -->";

// No trailing newline after MANAGED_END - callers that write a brand new
// file add their own EOF newline; `sync`'s splice reuses whatever trailing
// whitespace the existing file already had after the marker instead, so
// the two must not both contribute one or they compound on every sync.
export function wrapManaged(body: string): string {
  return `${MANAGED_START}\n${body.trim()}\n${MANAGED_END}`;
}

export const MANIFESTO_PRINCIPLES = [
  "Understand before acting. Never write code without full contextual knowledge.",
  "Research before building. Search the repository for existing patterns before creating new ones.",
  "Plan before execution. Draft a clear, step-by-step plan and assess risks before changing files.",
  "Verify before completing. Run tests, linters, and type checks. An unverified change is an incomplete change.",
  "Document as you go. Project memory must always reflect current reality.",
  "Leave the codebase better than you found it. Maintain continuous refactoring and clean code principles.",
];

export const LOOP_PHASES = [
  "Context Retrieval",
  "Repository Research",
  "Implementation Plan",
  "Risk & Impact Assessment",
  "Implementation",
  "Automated Testing & Verification",
  "Self-Healing & Bug Fixing",
  "Refactoring",
  "Memory & Documentation Update",
  "Task Summary",
];

export function renderLanguagePolicyLine(config: EngineeringLoopConfig): string {
  const policy = config.language_policy;
  if (!policy) return "All code, comments, and documentation must be written in English.";
  const parts = Object.entries(policy)
    .filter((entry): entry is [string, string] => typeof entry[1] === "string")
    .map(([key, value]) => `${key}=${value}`);
  return `Required languages by artifact: ${parts.join(", ")}.`;
}

export function renderCommandsBlock(config: EngineeringLoopConfig): string[] {
  const commands = config.commands ?? {};
  const lines: string[] = [];
  for (const [key, value] of Object.entries(commands)) {
    if (value) lines.push(`- ${key}: \`${value}\``);
  }
  return lines;
}

export function renderMemorySection(config: EngineeringLoopConfig): string {
  const dir = config.memory.directory;
  const files = config.memory.required_files.join(", ");
  return `Persistent project memory lives in \`${dir}/\` (${files}). Read it during Phase 1 (Context Retrieval) and update whatever it makes stale during Phase 9 (Memory & Documentation Update).`;
}
